services:
  web:
    build:
      context: .
      args:
        RUBY_VERSION: 3.2.4
    command: bash -c "rm -f /rails/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails:cached
      - bundle:/usr/local/bundle
    ports:
      - '3000:3000'
    depends_on:
      - db
    stdin_open: true
    tty: true
    restart: always
    environment:
      RAILS_ENV: development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always

volumes:
  bundle:
  postgres_volume:
